#!/system/bin/sh

set -eu

if [ "$(id -u)" -ne 0 ]; then
    exec su -c "$0" "$@"
fi

DIR=/data/local/androcli

GREEN="\033[32m"
BLUE="\033[34m"
RESET="\033[0m"

clear

printf "$GREEN"

if command -v figlet >/dev/null 2>&1; then
    figlet androidcli
else
cat <<'EOF'
       _           _     _      _ _
  __ _ _ __   __| |_ __ ___ (_) __| | ___| (_)
 / _` | '_ \ / _` | '__/ _ \| |/ _` |/ __| | |
| (_| | | | | (_| | | | (_) | | (_| | (__| | |
 \__,_|_| |_|\__,_|_|  \___/|_|\__,_|\___|_|_|
EOF
fi

printf "$RESET"

echo "AndroidCLI Installer"

SDK=$(getprop ro.build.version.sdk)

if [ "$SDK" -lt 29 ]; then
    echo "Android 10+ required"
    exit 1
fi

if [ ! -d /apex/com.android.runtime ]; then
    echo "APEX runtime missing"
    exit 1
fi


echo -e "$BLUE[*]$RESET Creating filesystem"

mkdir -p \
"$DIR/apex" \
"$DIR/system/bin" \
"$DIR/system/lib64" \
"$DIR/system/xbin" \
"$DIR/vendor/bin" \
"$DIR/vendor/lib64" \
"$DIR/vendor/xbin" \
"$DIR/linkerconfig" \
"$DIR/root" \
"$DIR/dev" \
"$DIR/proc" \
"$DIR/sys"


echo -e "$BLUE[*]$RESET Installing APEX"

cp -a /apex/com.android.runtime "$DIR/apex/"


echo -e "$BLUE[*]$RESET Installing binaries"

for bin in toybox linker linker64 sh; do
    [ -f "/system/bin/$bin" ] &&
    cp "/system/bin/$bin" "$DIR/system/bin/"
done


echo -e "$BLUE[*]$RESET Installing system libraries"

for lib in \
libc++.so \
libz.so \
liblog.so \
libselinux.so \
libcrypto.so \
libcurl.so \
libpcre2.so \
libpackagelistparser.so
do
    [ -f "/system/lib64/$lib" ] &&
    cp "/system/lib64/$lib" "$DIR/system/lib64/"
done


echo -e "$BLUE[*]$RESET Installing vendor libraries"

for lib in \
libc++.so \
libz.so \
liblog.so \
libselinux.so \
libcrypto.so
do
    [ -f "/vendor/lib64/$lib" ] &&
    cp "/vendor/lib64/$lib" "$DIR/vendor/lib64/"
done


echo -e "$BLUE[*]$RESET Installing toybox"

cd "$DIR/system/bin"

for cmd in $(./toybox); do
    ln -sf toybox "$cmd"
done

cd /


echo -e "$BLUE[*]$RESET Creating properties"


cat > "$DIR/system/build.prop" <<EOF
ro.product.model=generic_cli
ro.build.version.sdk=$SDK
ro.build.type=eng
ro.debuggable=1
ro.secure=0
ro.github=rebangkkuser/androidcli
EOF


cat > "$DIR/vendor/build.prop" <<EOF
ro.vendor.product.model=generic_cli
ro.vendor.build.type=eng
ro.vendor.github=rebangkkuser/androidcli
EOF


echo -e "$BLUE[*]$RESET Installing clim"


mkdir -p "$DIR/vendor/bin"

cp ./clim "$DIR/vendor/bin/clim"
chmod 755 "$DIR/vendor/bin/clim"


echo -e "$BLUE[*]$RESET Installing startacli"


cat > /data/local/bin/startacli <<'EOF'
#!/system/bin/sh

if [ "$(id -u)" != 0 ]; then
    exec su -c "$0" "$@"
fi

env -i \
HOME=/root \
ACLI_VBP=/vendor/build.prop \
ACLI_SBP=/system/build.prop \
LOCALHOST=127.0.0.1 \
PM=aclim \
chroot \
/data/local/androcli \
/system/bin/sh
EOF


chmod 755 /data/local/bin/startacli


echo "AndroidCLI installed."
